### ISSUE TITLE
Switch Recalbox => Rasplex

### ISSUE THREAD

**Issue by Plarkass** [LaurentMarchelli/recalbox-rasplex#1]
Hello,

It's actually not possible to switch from recalbox to rasplex.

**Comment by LaurentMarchelli** [comment]
Hi Plarkass,
Sorry for the inconvenience, it was a first draft, in fact in this version the switch is not yet implemented, I gonna push the new version this week-end.

**Comment by LaurentMarchelli** [comment]
Hi Plarkass,
Build with Rasplex version 1.0.3 is available on the rasplex branch (https://github.com/LaurentMarchelli/recalbox-rasplex/tree/rasplex) if u wanna have a try.
I tested the installation on a rpi3, it seems working, but I couldn't do further tests, as my plex server is down.
Let me know, regards

**Comment by Plarkass** [comment]
Hello,

I can try this evening when i Côme back to home.

I Will tell you if it is compliant with a rpi2.

Cu
Le 3 mai 2016 00:53, "Laurent Marchelli" notifications@github.com a
écrit :

**Comment by LaurentMarchelli** [comment]
Tested on rpi2 & rpi3 with Recalbox & Rasplex upgrade working. 
Everything is now available on master.
