### ISSUE TITLE
No rule to make target 'host-xz'

### ISSUE THREAD

**Issue by Vanclec** [LaurentMarchelli/recalbox-rasplex#10]
Hello there,

I just found your nice project and I wanted to give it a try. I tried to compile it with a fresh Debian Jessie. On make, all I got is:

make[1]: Leaving directory '/root/recalbox-rasplex'
make: *** No rule to make target 'host-xz', needed by 'dependencies'. Stopped.

On the menuconfig, I selected a Pi3, the default PHT theme and I also disabled any Powerswitch hardware.

Any clue?

Regards,
Chris.

**Comment by LaurentMarchelli** [comment]
Hi Chris,

Try to install [xz-utils](https://packages.debian.org/sid/xz-utils)
`
sudo apt-get install xz-utils
`
Let me know, if you have other issues.

Best Regards,
Laurent

**Comment by Vanclec** [comment]
Hi, Laurent! :)

Glad to read your answer. I installed the given package and the compilation went better.

Thank you for your help!

Regards,
Chris.

**Comment by LaurentMarchelli** [comment]
Thanks for your feedback, the readme has been updated.
