### ISSUE TITLE
Button to boot in recalbox

### ISSUE THREAD

**Issue by ralle2208** [LaurentMarchelli/recalbox-rasplex#14]
Hello,
I don't have any button to reboot in recalbox. Neither in Plex Black Edition nor in Aeon Nox.
Do you have a solution?
thx

**Comment by LaurentMarchelli** [comment]
Please attach your .config file so, I can have a check.

Best regards,

**Comment by ralle2208** [comment]
Thank you for the quick answer!
I did a few rebuilds and found a working build last night.
Right now, there is no more problem.
It works perfectly :) thanks a lot
best regards,
