### ISSUE TITLE
Update Recalbox

### ISSUE THREAD

**Issue by Plarkass** [LaurentMarchelli/recalbox-rasplex#2]
Thanks a lot for your project :+1: 
There is an update for Recalbox. Is it possible to recomile your project with the new version ?
It's not possible to do it directly in recalbox.

**Comment by LaurentMarchelli** [comment]
Hi,
I planned to be ready to the recalbox version 4.1.
Is it the recalboxOS 4.0.0-beta3 u are expecting ?

Envoyé de mon iPhone

**Comment by LaurentMarchelli** [comment]
recalboxOS 4.0.0-beta3 available, rasplex 1.0.3 coming soon.

**Comment by Plarkass** [comment]
Congats
Le 2 mai 2016 01:21, "Laurent Marchelli" notifications@github.com a
écrit :

**Comment by LaurentMarchelli** [comment]
Tested on rpi2 & rpi3 with Recalbox & Rasplex upgrade working. 
Everything is now available on master.
