### ISSUE TITLE
Support RetroPi?

### ISSUE THREAD

**Issue by eloo** [LaurentMarchelli/recalbox-rasplex#20]
Hi,
do you think it would be a possible to add RetroPi to the image?
So it would be great if the user can decide if he wants to integrate Recalbox or Retropi.

What do you think?

**Comment by LaurentMarchelli** [comment]
Hi Joseph,

Why not if you know how to do it. Make the Retropie integration project your own and I will be more than please to merge your pull request after a sanity check. ;-)

Best regards,
Laurent Marchelli

**Comment by eloo** [comment]
yep sounds good.. i will give it a try in a few days ;)

**Comment by LaurentMarchelli** [comment]
This may help with noobs configuration ... and maybe more ;-)
http://www.multibootpi.com/builds/quad-boot-raspbian-pixel-retropie-rasplex-kodi/#more-239

**Comment by LaurentMarchelli** [comment]
If u are still interested by multi boot with retropie, have a look to https://github.com/procount/pinn
