### ISSUE TITLE
Plex Black Edition Skin

### ISSUE THREAD

**Issue by eloo** [LaurentMarchelli/recalbox-rasplex#5]
Hi,
it would be awesome if you can provide a tutorial how to customize the Plex Black Edition Skin to get the switch to recalbox option.

Thanks for your effort and best regards.
Eloo

**Comment by LaurentMarchelli** [comment]
Hi Eloo,

Unfortunately I do not have the trick to add a custom button into the Plex Black Edition. 
I guess the best place to ask your question is here : https://forums.plex.tv/categories/plex-black-edition.
If you get a nice answer, I will be pleased to implement the solution into the next distribution.

Best regards,
Laurent

**Comment by eloo** [comment]
Got it work and updated the version of used images
Check out my pull request ;)

**Comment by LaurentMarchelli** [comment]
Great job, Thank you

**Comment by whoo** [comment]
Hi Guys,
This page "https://forums.plex.tv/categories/plex-black-edition" << does not exist anymore.
Is there a way to download Plex Black Edition theme/addons.

Regards,

**Comment by LaurentMarchelli** [comment]
Hi whoo,

Here is the linked used in recalbox-rasplex to download the black edition, it is all what I have.
You can download the zip from here, download works fine.
https://addons.openpht.tv/openpht-1.8/skin.plex_black_editionHT/skin.plex_black_editionHT-17.03.16.zip

Regards,
Laurent Marchelli
